"""Puertos de persistencia (interfaces abstractas).

Toda implementación inyecta el filtro tenant_id desde el contexto de la
petición: nunca se consulta sin ese filtro (regla de oro, sección 7).
"""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from nutriplan.domain.models import (
    Client,
    DayPlan,
    NutritionTargets,
    PlanCycle,
    PlanStatus,
)


class ClientRepository(Protocol):
    async def add(self, client: Client) -> None: ...
    async def get(self, client_id: UUID) -> Client | None: ...
    async def get_by_user(self, user_id: UUID) -> Client | None: ...
    async def list_all(self) -> list[Client]: ...
    async def update(self, client: Client) -> None: ...
    async def set_active_plan(self, client_id: UUID, plan_id: UUID | None) -> None: ...
    async def list_banned_food_ids(self, client_id: UUID) -> list[UUID]: ...
    async def ban_food(self, client_id: UUID, food_id: UUID) -> None: ...


class TargetsRepository(Protocol):
    async def add(self, targets: NutritionTargets) -> None: ...
    async def get(self, targets_id: UUID) -> NutritionTargets | None: ...
    async def latest_for_client(self, client_id: UUID) -> NutritionTargets | None: ...


class PlanRepository(Protocol):
    async def add(self, plan: PlanCycle) -> None: ...
    async def get(self, plan_id: UUID) -> PlanCycle | None: ...
    async def list_for_client(self, client_id: UUID) -> list[PlanCycle]: ...
    async def find_by_input_hash(self, input_hash: str) -> list[PlanCycle]: ...
    async def update_day(
        self,
        plan_id: UUID,
        day_index: int,
        day: DayPlan,
        *,
        mark_edited: bool = False,
    ) -> None: ...
    async def mark_edited(self, plan_id: UUID) -> None: ...
    async def set_status(self, plan_id: UUID, status: PlanStatus) -> None: ...
    async def set_version(self, plan_id: UUID, version: int) -> None: ...
    async def delete_draft_for_client(self, client_id: UUID) -> None: ...
    async def count_approved_for_client(self, client_id: UUID) -> int: ...
