"""catalogo: fibra, porciones y afinidad por comida

Revision ID: 110fb055d3be
Revises: d1818c5c59dd
Create Date: 2026-07-13 11:16:33.656211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '110fb055d3be'
down_revision: Union[str, Sequence[str], None] = 'd1818c5c59dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Ajustes a mano sobre el autogenerado, los dos por portabilidad a Postgres:
      - `meal_slots` salía NOT NULL sin server_default: las filas que ya existen
        se quedarían en NULL y la migración reventaría.
      - `is_free` salía con server_default=text('0'), que es sintaxis de SQLite;
        en Postgres `DEFAULT 0` sobre un boolean es un error de tipo. sa.false()
        se renderiza bien en los dos dialectos.
    El seed reescribe estos valores a continuación, pero la migración tiene que
    sostenerse por sí sola.
    """
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fiber_100g', sa.Float(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('portion_step_g', sa.Float(), server_default='10', nullable=False))
        batch_op.add_column(sa.Column('portion_min_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('meal_slots', sa.JSON(), server_default='[]', nullable=False))
        batch_op.add_column(sa.Column('is_free', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('free_text', sa.String(length=60), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_column('free_text')
        batch_op.drop_column('is_free')
        batch_op.drop_column('meal_slots')
        batch_op.drop_column('portion_min_g')
        batch_op.drop_column('portion_step_g')
        batch_op.drop_column('fiber_100g')

    # ### end Alembic commands ###
