"""tablas iniciales (seccion 7.4)

Revision ID: 4097b9d2f23d
Revises: 
Create Date: 2026-07-03 17:06:45.455653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4097b9d2f23d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_table('foods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_ref', sa.String(length=50), nullable=True),
    sa.Column('name_es', sa.String(length=200), nullable=False),
    sa.Column('name_norm', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('kcal_100g', sa.Float(), nullable=False),
    sa.Column('protein_100g', sa.Float(), nullable=False),
    sa.Column('carb_100g', sa.Float(), nullable=False),
    sa.Column('fat_100g', sa.Float(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('default_unit_g', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foods_category'), 'foods', ['category'], unique=False)
    op.create_index(op.f('ix_foods_name_norm'), 'foods', ['name_norm'], unique=False)
    op.create_index(op.f('ix_foods_tenant_id'), 'foods', ['tenant_id'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('result_id', sa.Uuid(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key')
    )
    op.create_index(op.f('ix_generation_jobs_status'), 'generation_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_generation_jobs_tenant_id'), 'generation_jobs', ['tenant_id'], unique=False)
    op.create_table('intake_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('source_filename', sa.String(length=300), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed', sa.JSON(), nullable=False),
    sa.Column('ambiguities', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intake_documents_status'), 'intake_documents', ['status'], unique=False)
    op.create_index(op.f('ix_intake_documents_tenant_id'), 'intake_documents', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('goal', sa.String(length=20), nullable=False),
    sa.Column('activity_level', sa.String(length=20), nullable=False),
    sa.Column('restrictions', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_tenant_id'), 'clients', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('client_food_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('food_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'food_id')
    )
    op.create_index(op.f('ix_client_food_preferences_client_id'), 'client_food_preferences', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_food_preferences_tenant_id'), 'client_food_preferences', ['tenant_id'], unique=False)
    op.create_table('nutrition_targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('daily', sa.JSON(), nullable=False),
    sa.Column('per_meal', sa.JSON(), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('config_version', sa.String(length=40), nullable=False),
    sa.Column('overrides', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_targets_client_id'), 'nutrition_targets', ['client_id'], unique=False)
    op.create_index(op.f('ix_nutrition_targets_tenant_id'), 'nutrition_targets', ['tenant_id'], unique=False)
    op.create_table('plan_cycles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('targets_id', sa.Uuid(), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config_version', sa.String(length=40), nullable=False),
    sa.Column('prompt_version', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['targets_id'], ['nutrition_targets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'input_hash', 'phase')
    )
    op.create_index(op.f('ix_plan_cycles_client_id'), 'plan_cycles', ['client_id'], unique=False)
    op.create_index(op.f('ix_plan_cycles_input_hash'), 'plan_cycles', ['input_hash'], unique=False)
    op.create_index(op.f('ix_plan_cycles_status'), 'plan_cycles', ['status'], unique=False)
    op.create_index(op.f('ix_plan_cycles_tenant_id'), 'plan_cycles', ['tenant_id'], unique=False)
    op.create_table('day_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('plan_cycle_id', sa.Uuid(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('totals', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['plan_cycle_id'], ['plan_cycles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_cycle_id', 'day_index')
    )
    op.create_index(op.f('ix_day_plans_plan_cycle_id'), 'day_plans', ['plan_cycle_id'], unique=False)
    op.create_index(op.f('ix_day_plans_tenant_id'), 'day_plans', ['tenant_id'], unique=False)
    op.create_table('export_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('plan_cycle_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_cycle_id'], ['plan_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_artifacts_plan_cycle_id'), 'export_artifacts', ['plan_cycle_id'], unique=False)
    op.create_index(op.f('ix_export_artifacts_tenant_id'), 'export_artifacts', ['tenant_id'], unique=False)
    op.create_table('meal_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('day_plan_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(length=20), nullable=False),
    sa.Column('portions', sa.JSON(), nullable=False),
    sa.Column('computed', sa.JSON(), nullable=False),
    sa.Column('free_salad', sa.Boolean(), nullable=False),
    sa.Column('free_protein', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['day_plan_id'], ['day_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_entries_day_plan_id'), 'meal_entries', ['day_plan_id'], unique=False)
    op.create_index(op.f('ix_meal_entries_tenant_id'), 'meal_entries', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_entries_tenant_id'), table_name='meal_entries')
    op.drop_index(op.f('ix_meal_entries_day_plan_id'), table_name='meal_entries')
    op.drop_table('meal_entries')
    op.drop_index(op.f('ix_export_artifacts_tenant_id'), table_name='export_artifacts')
    op.drop_index(op.f('ix_export_artifacts_plan_cycle_id'), table_name='export_artifacts')
    op.drop_table('export_artifacts')
    op.drop_index(op.f('ix_day_plans_tenant_id'), table_name='day_plans')
    op.drop_index(op.f('ix_day_plans_plan_cycle_id'), table_name='day_plans')
    op.drop_table('day_plans')
    op.drop_index(op.f('ix_plan_cycles_tenant_id'), table_name='plan_cycles')
    op.drop_index(op.f('ix_plan_cycles_status'), table_name='plan_cycles')
    op.drop_index(op.f('ix_plan_cycles_input_hash'), table_name='plan_cycles')
    op.drop_index(op.f('ix_plan_cycles_client_id'), table_name='plan_cycles')
    op.drop_table('plan_cycles')
    op.drop_index(op.f('ix_nutrition_targets_tenant_id'), table_name='nutrition_targets')
    op.drop_index(op.f('ix_nutrition_targets_client_id'), table_name='nutrition_targets')
    op.drop_table('nutrition_targets')
    op.drop_index(op.f('ix_client_food_preferences_tenant_id'), table_name='client_food_preferences')
    op.drop_index(op.f('ix_client_food_preferences_client_id'), table_name='client_food_preferences')
    op.drop_table('client_food_preferences')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clients_tenant_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_intake_documents_tenant_id'), table_name='intake_documents')
    op.drop_index(op.f('ix_intake_documents_status'), table_name='intake_documents')
    op.drop_table('intake_documents')
    op.drop_index(op.f('ix_generation_jobs_tenant_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_status'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index(op.f('ix_foods_tenant_id'), table_name='foods')
    op.drop_index(op.f('ix_foods_name_norm'), table_name='foods')
    op.drop_index(op.f('ix_foods_category'), table_name='foods')
    op.drop_table('foods')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
