"""esquema inicial

Revision ID: d1818c5c59dd
Revises: 
Create Date: 2026-07-13 10:49:09.623153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1818c5c59dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('foods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_ref', sa.String(length=50), nullable=True),
    sa.Column('name_es', sa.String(length=200), nullable=False),
    sa.Column('name_norm', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('kcal_100g', sa.Float(), nullable=False),
    sa.Column('protein_100g', sa.Float(), nullable=False),
    sa.Column('carb_100g', sa.Float(), nullable=False),
    sa.Column('fat_100g', sa.Float(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('default_unit_g', sa.Float(), nullable=True),
    sa.Column('unit_granularity', sa.String(length=10), nullable=False),
    sa.Column('unit_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_foods_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_foods_name_norm'), ['name_norm'], unique=False)
        batch_op.create_index(batch_op.f('ix_foods_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('generation_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('result_id', sa.Uuid(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key')
    )
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('intake_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('source_filename', sa.String(length=300), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed', sa.JSON(), nullable=False),
    sa.Column('ambiguities', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intake_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intake_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_intake_documents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('recipes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('macros', sa.JSON(), nullable=False),
    sa.Column('total_grams', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('compound_food_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('goal', sa.String(length=20), nullable=False),
    sa.Column('activity_level', sa.String(length=20), nullable=False),
    sa.Column('restrictions', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('client_food_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('food_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'food_id')
    )
    with op.batch_alter_table('client_food_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_food_preferences_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_food_preferences_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('nutrition_targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('daily', sa.JSON(), nullable=False),
    sa.Column('per_meal', sa.JSON(), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('config_version', sa.String(length=40), nullable=False),
    sa.Column('overrides', sa.JSON(), nullable=False),
    sa.Column('formula', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nutrition_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nutrition_targets_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nutrition_targets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('plan_cycles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('targets_id', sa.Uuid(), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config_version', sa.String(length=40), nullable=False),
    sa.Column('prompt_version', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['targets_id'], ['nutrition_targets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'input_hash', 'phase')
    )
    with op.batch_alter_table('plan_cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_cycles_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_cycles_input_hash'), ['input_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_cycles_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_cycles_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('day_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('plan_cycle_id', sa.Uuid(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('totals', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['plan_cycle_id'], ['plan_cycles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_cycle_id', 'day_index')
    )
    with op.batch_alter_table('day_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_day_plans_plan_cycle_id'), ['plan_cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_day_plans_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('export_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('plan_cycle_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_cycle_id'], ['plan_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_artifacts_plan_cycle_id'), ['plan_cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_artifacts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('meal_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('day_plan_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(length=20), nullable=False),
    sa.Column('portions', sa.JSON(), nullable=False),
    sa.Column('computed', sa.JSON(), nullable=False),
    sa.Column('free_salad', sa.Boolean(), nullable=False),
    sa.Column('free_protein', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['day_plan_id'], ['day_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_entries_day_plan_id'), ['day_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_entries_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_entries_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_meal_entries_day_plan_id'))

    op.drop_table('meal_entries')
    with op.batch_alter_table('export_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_artifacts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_export_artifacts_plan_cycle_id'))

    op.drop_table('export_artifacts')
    with op.batch_alter_table('day_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_day_plans_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_day_plans_plan_cycle_id'))

    op.drop_table('day_plans')
    with op.batch_alter_table('plan_cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_cycles_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_plan_cycles_status'))
        batch_op.drop_index(batch_op.f('ix_plan_cycles_input_hash'))
        batch_op.drop_index(batch_op.f('ix_plan_cycles_client_id'))

    op.drop_table('plan_cycles')
    with op.batch_alter_table('nutrition_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nutrition_targets_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_nutrition_targets_client_id'))

    op.drop_table('nutrition_targets')
    with op.batch_alter_table('client_food_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_food_preferences_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_client_food_preferences_client_id'))

    op.drop_table('client_food_preferences')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_tenant_id'))

    op.drop_table('clients')
    op.drop_table('tenants')
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_recipes_status'))

    op.drop_table('recipes')
    with op.batch_alter_table('intake_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intake_documents_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_intake_documents_status'))

    op.drop_table('intake_documents')
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_jobs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_generation_jobs_status'))

    op.drop_table('generation_jobs')
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_foods_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_foods_name_norm'))
        batch_op.drop_index(batch_op.f('ix_foods_category'))

    op.drop_table('foods')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_tenant_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
